import type {
  Resume,
  ResumeContact,
  ResumeExperience,
  ResumeEducation,
  ResumeSkillCategory,
  ResumeCertification,
} from '@/types/database'
import type { Locale } from '@/lib/i18n'
import { formatText } from '@/lib/format-text'

interface ProfessionalTemplateProps {
  resume: Resume
  locale: Locale
  dict: any
  titleFontSize?: number
  setTitleFontSize?: (size: number) => void
  titleGap?: number
  setTitleGap?: (gap: number) => void
  contactFontSize?: number
  setContactFontSize?: (size: number) => void
  sectionTitleFontSize?: number
  setSectionTitleFontSize?: (size: number) => void
  sectionDescFontSize?: number
  setSectionDescFontSize?: (size: number) => void
}

/**
 * Professional Template - Faithful to reference CV design with header modification
 *
 * Layout: Header + 2-column asymmetric (30% sidebar / 70% main content)
 *
 * Header (Full Width):
 *  - CV Title (centered, large)
 *  - Contact Info (Email, Phone, Location, LinkedIn, GitHub, Website)
 *
 * Sidebar (Navy Blue - Full Height):
 *  1. Name and Professional Title
 *  2. Key Achievements
 *  3. Skills
 *  4. Training/Courses (Certifications)
 *
 * Main Content (White):
 *  1. Summary (with bottom border)
 *  2. Experience (with bottom border)
 *  3. Education (with bottom border)
 */
export function ProfessionalTemplate({
  resume,
  locale,
  dict,
  titleFontSize = 24,
  setTitleFontSize,
  titleGap = 8,
  setTitleGap,
  contactFontSize = 12,
  setContactFontSize,
  sectionTitleFontSize = 16,
  setSectionTitleFontSize,
  sectionDescFontSize = 14,
  setSectionDescFontSize,
}: ProfessionalTemplateProps) {
  const contact = (resume.contact as unknown as ResumeContact) || {}
  // Filter to show only visible items
  const experiences = ((resume.experience as unknown as ResumeExperience[]) || []).filter(exp => exp.visible !== false)
  const education = ((resume.education as unknown as ResumeEducation[]) || []).filter(edu => edu.visible !== false)
  const skills = ((resume.skills as unknown as ResumeSkillCategory[]) || []).filter(skill => skill.visible !== false)
  const certifications = ((resume.certifications as unknown as ResumeCertification[]) || []).filter(cert => cert.visible !== false)

  // Key Achievements - To be generated by AI transformation
  const keyAchievements = generateKeyAchievements(experiences, skills)

  return (
    <div
      className="professional-template mx-auto shadow-lg print:shadow-none print:bg-transparent"
      style={{
        width: '816px',
        minHeight: '1056px',
        position: 'relative',
        backgroundColor: 'white'
      }}
    >
      {/* Sidebar - Full height from top to bottom */}
      <div
        className="p-6 text-white print:p-5"
        style={{
          position: 'absolute',
          top: 0,
          bottom: 0,
          left: 0,
          width: '30%',
          backgroundColor: 'oklch(0.25 0.05 240)'
        }}
      >
          {/* NAME AND TITLE SECTION */}
          <div className="mb-8 border-b border-white/20 pb-6">
            {/* Name - Large, Uppercase, Bold */}
            <h2 className="mb-2 text-2xl font-bold uppercase leading-tight tracking-tight">
              {contact.name || 'YOUR NAME'}
            </h2>

            {/* Professional Title - Cyan Accent */}
            <p
              className="mb-2 text-sm leading-snug"
              style={{ color: 'oklch(0.7 0.15 200)' }}
            >
              {contact.name ? (resume.title || 'Professional Title') : ''}
            </p>
          </div>

          {/* KEY ACHIEVEMENTS SECTION */}
          {keyAchievements.length > 0 && (
            <div className="mb-8">
              <h2 className="mb-4 text-sm font-bold tracking-wide capitalize">
                {dict.resumes.template.keyAchievements}
              </h2>
              <div className="space-y-4">
                {keyAchievements.map((achievement, index) => (
                  <div key={index}>
                    <div className="mb-1 flex items-start gap-2">
                      <span className="mt-0.5 text-xs opacity-70">▸</span>
                      <h3 className="text-sm font-bold leading-snug">
                        {achievement.title}
                      </h3>
                    </div>
                    {achievement.description && (
                      <p className="ml-4 text-xs leading-relaxed opacity-90">
                        {achievement.description}
                      </p>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* SKILLS SECTION */}
          {skills.filter(s => s.category && s.items && s.items.length > 0).length > 0 && (
            <div className="mb-8">
              <h2 className="mb-4 text-sm font-bold tracking-wide capitalize">
                {dict.resumes.template.skills}
              </h2>
              <div className="text-xs leading-relaxed">
                {skills
                  .filter(skillCategory =>
                    skillCategory.category &&
                    skillCategory.items &&
                    skillCategory.items.length > 0
                  )
                  .map((skillCategory, index) => (
                    <div key={index} className="mb-3">
                      <p className="mb-1 font-semibold opacity-90">
                        {skillCategory.category}:
                      </p>
                      <p className="opacity-80">{skillCategory.items.join(', ')}</p>
                    </div>
                  ))}
              </div>
            </div>
          )}

          {/* TRAINING / COURSES SECTION */}
          {certifications.length > 0 && (
            <div>
              <h2 className="mb-4 text-sm font-bold tracking-wide capitalize">
                {dict.resumes.template.training}
              </h2>
              <div className="space-y-4">
                {certifications.slice(0, 3).map((cert, index) => (
                  <div key={index}>
                    <h3 className="mb-1 text-sm font-bold leading-snug">
                      {cert.name}
                    </h3>
                    <p className="text-xs opacity-90">{cert.issuer}</p>
                    {cert.date && (
                      <p className="text-xs opacity-75">
                        {new Date(cert.date + '-01').toLocaleDateString(locale, {
                          month: 'long',
                          year: 'numeric',
                        })}
                      </p>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

      {/* Main Content - Positioned to the right of sidebar */}
      <div
        className="p-8 print:p-6"
        style={{
          marginLeft: '30%',
          position: 'relative',
          zIndex: 1
        }}
      >
          {/* HEADER: CV Title and Contact Info */}
          <div className="mb-8 border-b-2 pb-6" style={{ borderColor: 'oklch(0.25 0.05 240)', position: 'relative' }}>
            <h1 className="font-bold uppercase tracking-tight" style={{ color: 'oklch(0.25 0.05 240)', fontSize: `${titleFontSize}px`, marginBottom: `${titleGap}px`, position: 'relative' }}>
              {resume.title || 'CV TITLE'}

              {/* Font Size Slider - Positioned outside CV to the right */}
              {setTitleFontSize && (
                <div
                  className="print:hidden"
                  style={{
                    position: 'absolute',
                    left: '100%',
                    bottom: 0,
                    marginLeft: '48px',
                    whiteSpace: 'nowrap'
                  }}
                >
                  <div className="text-xs text-slate-600 font-medium mb-0.5">
                    {dict.resumes?.sliders?.title || 'Title'}
                  </div>
                  <div className="flex items-center gap-2 bg-white rounded-lg border border-slate-200 px-3 py-1 shadow-sm">
                    <input
                      type="range"
                      min="16"
                      max="48"
                      step="2"
                      value={titleFontSize}
                      onChange={(e) => setTitleFontSize(Number(e.target.value))}
                      className="w-32 h-1.5 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-slate-600"
                    />
                    <span className="text-xs text-slate-600 font-mono">
                      {titleFontSize}px
                    </span>
                  </div>
                </div>
              )}
            </h1>

            {/* Title Gap Slider - Vertical slider to the right of Title and Contact sliders */}
            {setTitleGap && (
              <div
                className="print:hidden"
                style={{
                  position: 'absolute',
                  left: '100%',
                  top: 0,
                  marginLeft: '260px',
                  zIndex: 10,
                  width: '48px'
                }}
              >
                <div className="text-xs text-slate-600 font-medium mb-0.5 text-center">
                  Title Gap
                </div>
                <div className="flex flex-col items-center justify-between bg-white rounded-lg border border-slate-200 px-2 py-3 shadow-sm" style={{ height: `${96 + titleGap}px` }}>
                  <input
                    type="range"
                    min="0"
                    max="32"
                    step="2"
                    value={titleGap}
                    onChange={(e) => setTitleGap(Number(e.target.value))}
                    className="appearance-none cursor-pointer accent-slate-600"
                    style={{
                      writingMode: 'vertical-lr',
                      width: '1.5rem',
                      height: `${titleGap + 48}px`,
                      background: 'linear-gradient(to top, oklch(0.85 0 0) 0%, oklch(0.85 0 0) 100%)',
                      borderRadius: '0.5rem'
                    }}
                  />
                  <span className="text-xs text-slate-600 font-mono mt-2">
                    {titleGap}px
                  </span>
                </div>
              </div>
            )}

            {/* Contact Information */}
            <div className="flex flex-wrap gap-x-4 gap-y-1" style={{ color: 'oklch(0.4 0 0)', fontSize: `${contactFontSize}px`, position: 'relative' }}>
              {/* Font Size Slider for Contact - Positioned outside CV to the right */}
              {setContactFontSize && (
                <div
                  className="print:hidden"
                  style={{
                    position: 'absolute',
                    left: '100%',
                    top: 0,
                    marginLeft: '48px',
                    whiteSpace: 'nowrap'
                  }}
                >
                  <div className="text-xs text-slate-600 font-medium mb-0.5">
                    {dict.resumes?.sliders?.contactDetails || 'Contact details'}
                  </div>
                  <div className="flex items-center gap-2 bg-white rounded-lg border border-slate-200 px-3 py-1 shadow-sm">
                    <input
                      type="range"
                      min="10"
                      max="18"
                      step="1"
                      value={contactFontSize}
                      onChange={(e) => setContactFontSize(Number(e.target.value))}
                      className="w-32 h-1.5 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-slate-600"
                    />
                    <span className="text-xs text-slate-600 font-mono">
                      {contactFontSize}px
                    </span>
                  </div>
                </div>
              )}
              {contact.email && (
                <div className="flex items-center gap-1.5">
                  <span>✉️</span>
                  <a href={`mailto:${contact.email}`} className="hover:underline">
                    {contact.email}
                  </a>
                </div>
              )}
              {contact.phone && (
                <div className="flex items-center gap-1.5">
                  <span>📞</span>
                  <span>{contact.phone}</span>
                </div>
              )}
              {contact.location && (
                <div className="flex items-center gap-1.5">
                  <span>📍</span>
                  <span>{contact.location}</span>
                </div>
              )}
              {contact.linkedin && (
                <div className="flex items-center gap-1.5">
                  <span>🔗</span>
                  <span>{contact.linkedin}</span>
                </div>
              )}
              {contact.github && (
                <div className="flex items-center gap-1.5">
                  <span>💻</span>
                  <span>{contact.github}</span>
                </div>
              )}
              {contact.website && (
                <div className="flex items-center gap-1.5">
                  <span>🌐</span>
                  <a href={contact.website} className="hover:underline">
                    {contact.website}
                  </a>
                </div>
              )}
            </div>
          </div>

          {/* SUMMARY SECTION */}
          {resume.summary && (
            <div className="mb-8">
              <h2
                className="mb-3 font-bold tracking-wide pb-2 border-b capitalize"
                style={{ color: 'oklch(0.2 0 0)', borderColor: 'oklch(0.7 0.05 240)', fontSize: `${sectionTitleFontSize}px`, position: 'relative' }}
              >
                {dict.resumes.template.summary}

                {/* Font Size Slider for Section Titles - Positioned outside CV to the right */}
                {setSectionTitleFontSize && (
                  <div
                    className="print:hidden"
                    style={{
                      position: 'absolute',
                      left: '100%',
                      bottom: 0,
                      marginLeft: '48px',
                      whiteSpace: 'nowrap'
                    }}
                  >
                    <div className="text-xs text-slate-600 font-medium mb-0.5">
                      {dict.resumes?.sliders?.sectionTitle || 'Section title'}
                    </div>
                    <div className="flex items-center gap-2 bg-white rounded-lg border border-slate-200 px-3 py-1 shadow-sm">
                      <input
                        type="range"
                        min="12"
                        max="24"
                        step="1"
                        value={sectionTitleFontSize}
                        onChange={(e) => setSectionTitleFontSize(Number(e.target.value))}
                        className="w-32 h-1.5 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-slate-600"
                      />
                      <span className="text-xs text-slate-600 font-mono">
                        {sectionTitleFontSize}px
                      </span>
                    </div>
                  </div>
                )}
              </h2>
              <div
                className="leading-relaxed text-justify"
                style={{
                  fontSize: `${sectionDescFontSize}px`,
                  color: 'oklch(0.3 0 0)',
                  lineHeight: '1.6',
                  position: 'relative'
                }}
              >
                {formatText(resume.summary)}

                {/* Font Size Slider for Section Descriptions - Positioned outside CV to the right */}
                {setSectionDescFontSize && (
                  <div
                    className="print:hidden"
                    style={{
                      position: 'absolute',
                      left: '100%',
                      top: 0,
                      marginLeft: '48px',
                      whiteSpace: 'nowrap'
                    }}
                  >
                    <div className="text-xs text-slate-600 font-medium mb-0.5">
                      {dict.resumes?.sliders?.description || 'Description'}
                    </div>
                    <div className="flex items-center gap-2 bg-white rounded-lg border border-slate-200 px-3 py-1 shadow-sm">
                      <input
                        type="range"
                        min="10"
                        max="18"
                        step="1"
                        value={sectionDescFontSize}
                        onChange={(e) => setSectionDescFontSize(Number(e.target.value))}
                        className="w-32 h-1.5 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-slate-600"
                      />
                      <span className="text-xs text-slate-600 font-mono">
                        {sectionDescFontSize}px
                      </span>
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* EXPERIENCE SECTION */}
          {experiences.length > 0 && (
            <div className="mb-8">
              <h2
                className="mb-4 font-bold tracking-wide pb-2 border-b capitalize"
                style={{ color: 'oklch(0.2 0 0)', borderColor: 'oklch(0.7 0.05 240)', fontSize: `${sectionTitleFontSize}px` }}
              >
                {dict.resumes.template.experience}
              </h2>
              <div className="space-y-6">
                {experiences.map((exp, index) => (
                  <div key={index}>
                    {/* Job Title + Dates */}
                    <div className="mb-1 flex items-start justify-between">
                      <h3
                        className="text-base font-bold"
                        style={{ color: 'oklch(0.2 0 0)' }}
                      >
                        {exp.position}
                      </h3>
                      <span
                        className="text-sm"
                        style={{ color: 'oklch(0.5 0 0)' }}
                      >
                        {formatDateRange(exp, locale, dict)}
                      </span>
                    </div>

                    {/* Company Name */}
                    <p
                      className="mb-2 text-sm"
                      style={{ color: 'oklch(0.4 0 0)' }}
                    >
                      {exp.company}
                      {exp.location && ` • ${exp.location}`}
                    </p>

                    {/* Achievements Bullets (priority) or Description */}
                    {exp.achievements && exp.achievements.length > 0 ? (
                      <ul className="space-y-1">
                        {exp.achievements.map((achievement, i) => (
                          <li
                            key={i}
                            className="flex gap-2"
                            style={{
                              fontSize: `${sectionDescFontSize}px`,
                              color: 'oklch(0.3 0 0)',
                              lineHeight: '1.5',
                            }}
                          >
                            <span style={{ color: 'oklch(0.2 0 0)' }}>•</span>
                            <span>{formatText(achievement)}</span>
                          </li>
                        ))}
                      </ul>
                    ) : exp.description ? (
                      <div
                        className="mb-2 leading-relaxed text-justify"
                        style={{
                          fontSize: `${sectionDescFontSize}px`,
                          color: 'oklch(0.3 0 0)',
                          lineHeight: '1.5',
                        }}
                      >
                        {formatText(exp.description)}
                      </div>
                    ) : null}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* EDUCATION SECTION */}
          {education.length > 0 && (
            <div>
              <h2
                className="mb-4 font-bold tracking-wide pb-2 border-b capitalize"
                style={{ color: 'oklch(0.2 0 0)', borderColor: 'oklch(0.7 0.05 240)', fontSize: `${sectionTitleFontSize}px` }}
              >
                {dict.resumes.template.education}
              </h2>
              <div className="space-y-4">
                {education.map((edu, index) => (
                  <div key={index}>
                    {/* Degree + Dates */}
                    <div className="mb-1 flex items-start justify-between">
                      <h3
                        className="text-base font-bold"
                        style={{ color: 'oklch(0.2 0 0)' }}
                      >
                        {edu.degree}
                        {edu.field && ` ${dict.resumes.template.in} ${edu.field}`}
                      </h3>
                      <span
                        className="text-sm"
                        style={{ color: 'oklch(0.5 0 0)' }}
                      >
                        {formatEducationDates(edu, locale, dict)}
                      </span>
                    </div>

                    {/* University + Location */}
                    <div className="flex items-start justify-between">
                      <a
                        href="#"
                        className="text-sm font-medium hover:underline"
                        style={{ color: 'oklch(0.7 0.15 200)' }}
                      >
                        {edu.school}
                      </a>
                      {edu.location && (
                        <span
                          className="text-sm"
                          style={{ color: 'oklch(0.5 0 0)' }}
                        >
                          {edu.location}
                        </span>
                      )}
                    </div>

                    {/* GPA if available */}
                    {edu.gpa && (
                      <p
                        className="mt-1 text-xs"
                        style={{ color: 'oklch(0.5 0 0)' }}
                      >
                        {dict.resumes.template.gpa}: {edu.gpa}
                      </p>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}
      </div>
    </div>
  )
}

// ========================================
// HELPER FUNCTIONS
// ========================================

/**
 * Generate Key Achievements from experience data
 */
function generateKeyAchievements(
  experiences: ResumeExperience[],
  skills: ResumeSkillCategory[]
): { title: string; description: string }[] {
  const achievements: { title: string; description: string }[] = []

  // Extract from experiences
  experiences.slice(0, 3).forEach((exp) => {
    if (exp.achievements && exp.achievements.length > 0) {
      const firstAchievement = exp.achievements[0]
      const words = firstAchievement.split(' ')
      const title = words.slice(0, 4).join(' ') + (words.length > 4 ? '...' : '')

      achievements.push({
        title: title,
        description: firstAchievement.substring(0, 80) + '...',
      })
    }
  })

  // If not enough achievements, add skill-based ones
  if (achievements.length < 4 && skills.length > 0) {
    const topSkillCategory = skills[0]
    achievements.push({
      title: `${topSkillCategory.category} Expert`,
      description: `Proficient in ${topSkillCategory.items.slice(0, 3).join(', ')}`,
    })
  }

  return achievements.slice(0, 4)
}

/**
 * Format date range for experience
 */
function formatDateRange(exp: ResumeExperience, locale: Locale, dict: any): string {
  const startDate = exp.startDate
    ? new Date(exp.startDate + '-01').toLocaleDateString(locale, {
        month: '2-digit',
        year: 'numeric',
      })
    : ''

  const endDate = exp.current
    ? dict.resumes.template.present
    : exp.endDate
      ? new Date(exp.endDate + '-01').toLocaleDateString(locale, {
          month: '2-digit',
          year: 'numeric',
        })
      : dict.resumes.template.present

  return `${startDate} - ${endDate}`
}

/**
 * Format date range for education
 */
function formatEducationDates(edu: ResumeEducation, locale: Locale, dict: any): string {
  const startDate = edu.startDate
    ? new Date(edu.startDate + '-01').toLocaleDateString(locale, {
        month: '2-digit',
        year: 'numeric',
      })
    : ''

  const endDate = edu.endDate
    ? new Date(edu.endDate + '-01').toLocaleDateString(locale, {
        month: '2-digit',
        year: 'numeric',
      })
    : dict.resumes.template.present

  return `${startDate} - ${endDate}`
}
